### ISSUE TITLE
Error in beforeDestroy hook

### ISSUE THREAD

**Issue by onelastjedi** [PierBover/vuex-apollo-example-project#4]
Error in beforeDestroy hook: "TypeError: observer.unsubscribe is not a function" appears.

**Comment by onelastjedi** [comment]
I think, that we need set anything like this before:
 `handler = subscribeToFruits(context){ fruitsSubscriptionObserver.subscribe....`

Then call: 
`unsubscribeFromFruits(context){
			handler.unsubscribe();
		},`

**Comment by PierBover** [comment]
When the component `App.vue` is created [it starts the subscription](https://github.com/PierBover/vuex-apollo-example-project/blob/master/src/App.vue#L21-L24) in [the store](https://github.com/PierBover/vuex-apollo-example-project/blob/master/store.js#L74-L97).

When it is destroyed it asks for an unsubscription to the store. It works here and from the ApolloClient source it's clear the [unsubscribe method is in the observable](https://github.com/apollographql/apollo-client/blob/master/src/util/Observable.ts#L43-L45).

Maybe you are asking for an unsubscription to the store before you have asked for a subscription?

**Comment by onelastjedi** [comment]
@PierBover, a agree with your explanation, but i just added the button that call `this.$store.dispatch('unsubscribeFromFruits')`.

You can check working example here: https://dist-ucldniqqpe.now.sh

In other case, when we added `console.log(fruitsSubscriptionObserver.unsubscribe())` inside `next(data)`, where we absolutely sure that asked for subscription — the same problem appears.

**Comment by PierBover** [comment]
Ok. I'll give it a look.

**Comment by onelastjedi** [comment]
How is it going?

**Comment by PierBover** [comment]
You were right. After fiddling a bit more I bumped into the problem.

I was confused by the **observable** and the actual **observer**.

I have updated the example with a button to subscribe and unsubscribe.
